apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-demo-ui
  namespace: kube-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-demo-ui-readonly
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "services", "namespaces", "events" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "apps" ]
  resources: [ "deployments", "replicasets", "statefulsets", "daemonsets" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-demo-ui-readonly-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-demo-ui-readonly
subjects:
- kind: ServiceAccount
  name: kube-demo-ui
  namespace: kube-demo
